[2021-07-13 09:56:26,868] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: psotgrressdftest.select_ticker 2021-07-13T09:56:23.179426+00:00 [queued]>
[2021-07-13 09:56:26,908] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: psotgrressdftest.select_ticker 2021-07-13T09:56:23.179426+00:00 [queued]>
[2021-07-13 09:56:26,909] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-13 09:56:26,910] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-07-13 09:56:26,910] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-13 09:56:26,928] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): select_ticker> on 2021-07-13T09:56:23.179426+00:00
[2021-07-13 09:56:26,943] {standard_task_runner.py:52} INFO - Started process 3948 to run task
[2021-07-13 09:56:26,948] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'psotgrressdftest', 'select_ticker', '2021-07-13T09:56:23.179426+00:00', '--job-id', '164', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/POSTGRESRSERS.py', '--cfg-path', '/tmp/tmp1qhwdyp0', '--error-file', '/tmp/tmpsfzr17kt']
[2021-07-13 09:56:26,949] {standard_task_runner.py:77} INFO - Job 164: Subtask select_ticker
[2021-07-13 09:56:27,028] {logging_mixin.py:104} INFO - Running <TaskInstance: psotgrressdftest.select_ticker 2021-07-13T09:56:23.179426+00:00 [running]> on host a2cbcfd4d6f4
[2021-07-13 09:56:27,108] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=psotgrressdftest
AIRFLOW_CTX_TASK_ID=select_ticker
AIRFLOW_CTX_EXECUTION_DATE=2021-07-13T09:56:23.179426+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-13T09:56:23.179426+00:00
[2021-07-13 09:56:27,119] {taskinstance.py:1481} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/POSTGRESRSERS.py", line 61, in select_ticker
    current_ticker = current_ticker[0]
TypeError: 'NoneType' object is not subscriptable
[2021-07-13 09:56:27,132] {taskinstance.py:1531} INFO - Marking task as FAILED. dag_id=psotgrressdftest, task_id=select_ticker, execution_date=20210713T095623, start_date=20210713T095626, end_date=20210713T095627
[2021-07-13 09:56:27,200] {local_task_job.py:151} INFO - Task exited with return code 1
