[2021-07-15 14:05:06,333] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: psotgrressdftest.extract_trends 2021-07-15T14:03:00+00:00 [queued]>
[2021-07-15 14:05:06,385] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: psotgrressdftest.extract_trends 2021-07-15T14:03:00+00:00 [queued]>
[2021-07-15 14:05:06,387] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-15 14:05:06,389] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-07-15 14:05:06,390] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-15 14:05:06,467] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): extract_trends> on 2021-07-15T14:03:00+00:00
[2021-07-15 14:05:06,502] {standard_task_runner.py:52} INFO - Started process 4203 to run task
[2021-07-15 14:05:06,522] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'psotgrressdftest', 'extract_trends', '2021-07-15T14:03:00+00:00', '--job-id', '437', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/POSTGRESRSERS.py', '--cfg-path', '/tmp/tmp6j2up7af', '--error-file', '/tmp/tmphnml240i']
[2021-07-15 14:05:06,527] {standard_task_runner.py:77} INFO - Job 437: Subtask extract_trends
[2021-07-15 14:05:06,852] {logging_mixin.py:104} INFO - Running <TaskInstance: psotgrressdftest.extract_trends 2021-07-15T14:03:00+00:00 [running]> on host a2cbcfd4d6f4
[2021-07-15 14:05:07,257] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=psotgrressdftest
AIRFLOW_CTX_TASK_ID=extract_trends
AIRFLOW_CTX_EXECUTION_DATE=2021-07-15T14:03:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-15T14:03:00+00:00
[2021-07-15 14:05:07,343] {logging_mixin.py:104} INFO - ['3PLAND.BO']
[2021-07-15 14:05:26,170] {logging_mixin.py:104} INFO - AAAAAAAAAAAAAAAAAAAAAAAAAAAA[0.0, 0.0, 0.0, 0.0, 0.0]
[2021-07-15 14:05:26,193] {taskinstance.py:1481} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/POSTGRESRSERS.py", line 148, in extract_trends
    cur.execute("UPDATE stages SET trendsStage = trendsStage + 1 WHERE keyword = '" + ticker.replace("'", "''") + "'")
AttributeError: 'list' object has no attribute 'replace'
[2021-07-15 14:05:26,257] {taskinstance.py:1531} INFO - Marking task as FAILED. dag_id=psotgrressdftest, task_id=extract_trends, execution_date=20210715T140300, start_date=20210715T140506, end_date=20210715T140526
[2021-07-15 14:05:26,383] {local_task_job.py:151} INFO - Task exited with return code 1
