[2021-07-12 13:33:53,608] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: ticker_yahoo.extract_task 2021-07-12T13:33:50.605650+00:00 [queued]>
[2021-07-12 13:33:53,654] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: ticker_yahoo.extract_task 2021-07-12T13:33:50.605650+00:00 [queued]>
[2021-07-12 13:33:53,655] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-12 13:33:53,656] {taskinstance.py:1068} INFO - Starting attempt 1 of 2
[2021-07-12 13:33:53,657] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-12 13:33:53,680] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): extract_task> on 2021-07-12T13:33:50.605650+00:00
[2021-07-12 13:33:53,711] {standard_task_runner.py:52} INFO - Started process 472 to run task
[2021-07-12 13:33:53,719] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ticker_yahoo', 'extract_task', '2021-07-12T13:33:50.605650+00:00', '--job-id', '21', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/seleniumtest.py', '--cfg-path', '/tmp/tmprfarvz65', '--error-file', '/tmp/tmph06ykye0']
[2021-07-12 13:33:53,721] {standard_task_runner.py:77} INFO - Job 21: Subtask extract_task
[2021-07-12 13:33:53,861] {logging_mixin.py:104} INFO - Running <TaskInstance: ticker_yahoo.extract_task 2021-07-12T13:33:50.605650+00:00 [running]> on host f29b1d03ad56
[2021-07-12 13:33:54,018] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ticker_yahoo
AIRFLOW_CTX_TASK_ID=extract_task
AIRFLOW_CTX_EXECUTION_DATE=2021-07-12T13:33:50.605650+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-12T13:33:50.605650+00:00
[2021-07-12 13:35:09,337] {logging_mixin.py:104} INFO - None
[2021-07-12 13:35:41,671] {logging_mixin.py:104} INFO - None
[2021-07-12 13:36:13,443] {logging_mixin.py:104} INFO - None
[2021-07-12 13:36:45,202] {logging_mixin.py:104} INFO - None
[2021-07-12 13:37:16,838] {logging_mixin.py:104} INFO - None
[2021-07-12 13:37:48,391] {logging_mixin.py:104} INFO - None
[2021-07-12 13:38:20,553] {logging_mixin.py:104} INFO - None
[2021-07-12 13:38:54,417] {logging_mixin.py:104} INFO - None
[2021-07-12 13:39:27,474] {logging_mixin.py:104} INFO - None
[2021-07-12 13:40:00,449] {taskinstance.py:1481} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/seleniumtest.py", line 59, in extract
    ticker = str(ticker[0].text)
IndexError: list index out of range
[2021-07-12 13:40:00,528] {taskinstance.py:1531} INFO - Marking task as UP_FOR_RETRY. dag_id=ticker_yahoo, task_id=extract_task, execution_date=20210712T133350, start_date=20210712T133353, end_date=20210712T134000
[2021-07-12 13:40:00,910] {local_task_job.py:151} INFO - Task exited with return code 1
