[2021-07-22 13:33:18,311] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: psotgrressdftest.select_ticker 2021-07-22T13:33:15.123959+00:00 [queued]>
[2021-07-22 13:33:18,343] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: psotgrressdftest.select_ticker 2021-07-22T13:33:15.123959+00:00 [queued]>
[2021-07-22 13:33:18,344] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-22 13:33:18,345] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-07-22 13:33:18,346] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-22 13:33:18,362] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): select_ticker> on 2021-07-22T13:33:15.123959+00:00
[2021-07-22 13:33:18,376] {standard_task_runner.py:52} INFO - Started process 411 to run task
[2021-07-22 13:33:18,380] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'psotgrressdftest', 'select_ticker', '2021-07-22T13:33:15.123959+00:00', '--job-id', '2034', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/POSTGRESRSERS.py', '--cfg-path', '/tmp/tmp_pm3c3w8', '--error-file', '/tmp/tmpl9nsik8p']
[2021-07-22 13:33:18,382] {standard_task_runner.py:77} INFO - Job 2034: Subtask select_ticker
[2021-07-22 13:33:18,497] {logging_mixin.py:104} INFO - Running <TaskInstance: psotgrressdftest.select_ticker 2021-07-22T13:33:15.123959+00:00 [running]> on host 5795a622f846
[2021-07-22 13:33:18,629] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=psotgrressdftest
AIRFLOW_CTX_TASK_ID=select_ticker
AIRFLOW_CTX_EXECUTION_DATE=2021-07-22T13:33:15.123959+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-22T13:33:12.135172+00:00
[2021-07-22 13:33:18,657] {base.py:78} INFO - Using connection to: id: postgres. Host: postgres, Port: 5432, Schema: postgres, Login: ***, Password: ***, extra: {}
[2021-07-22 13:33:18,667] {dbapi.py:204} INFO - Running statement: SELECT COUNT(*) FROM stages, parameters: None
[2021-07-22 13:33:18,669] {dbapi.py:212} INFO - Rows affected: 1
[2021-07-22 13:33:18,671] {logging_mixin.py:104} INFO - None
[2021-07-22 13:33:18,672] {taskinstance.py:1481} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/POSTGRESRSERS.py", line 66, in select_ticker
    cur.execute("SELECT keyword from tickers1 WHERE ID = " + completedcount)
TypeError: must be str, not NoneType
[2021-07-22 13:33:18,686] {taskinstance.py:1531} INFO - Marking task as FAILED. dag_id=psotgrressdftest, task_id=select_ticker, execution_date=20210722T133315, start_date=20210722T133318, end_date=20210722T133318
[2021-07-22 13:33:18,754] {local_task_job.py:151} INFO - Task exited with return code 1
