[2021-07-12 14:10:13,942] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: ticker_yahoo.extract_task 2021-07-12T14:09:31.916476+00:00 [queued]>
[2021-07-12 14:10:14,081] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: ticker_yahoo.extract_task 2021-07-12T14:09:31.916476+00:00 [queued]>
[2021-07-12 14:10:14,083] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-12 14:10:14,085] {taskinstance.py:1068} INFO - Starting attempt 1 of 2
[2021-07-12 14:10:14,099] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-12 14:10:14,243] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): extract_task> on 2021-07-12T14:09:31.916476+00:00
[2021-07-12 14:10:14,396] {standard_task_runner.py:52} INFO - Started process 2464 to run task
[2021-07-12 14:10:14,454] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ticker_yahoo', 'extract_task', '2021-07-12T14:09:31.916476+00:00', '--job-id', '24', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/seleniumtest.py', '--cfg-path', '/tmp/tmprzsso3y2', '--error-file', '/tmp/tmpy_qwuina']
[2021-07-12 14:10:14,463] {standard_task_runner.py:77} INFO - Job 24: Subtask extract_task
[2021-07-12 14:10:14,851] {logging_mixin.py:104} INFO - Running <TaskInstance: ticker_yahoo.extract_task 2021-07-12T14:09:31.916476+00:00 [running]> on host f29b1d03ad56
[2021-07-12 14:10:15,325] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ticker_yahoo
AIRFLOW_CTX_TASK_ID=extract_task
AIRFLOW_CTX_EXECUTION_DATE=2021-07-12T14:09:31.916476+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-12T14:09:31.916476+00:00
[2021-07-12 14:11:40,699] {logging_mixin.py:104} INFO - 20MICRONS.NS
[2021-07-12 14:11:40,702] {logging_mixin.py:104} INFO - 20 Microns Limited (20MICRONS.NS)
[2021-07-12 14:12:15,678] {logging_mixin.py:104} INFO - 21STCENMGM.NS
[2021-07-12 14:12:15,679] {logging_mixin.py:104} INFO - 21ST CENTURY MANAG (21STCENMGM.NS)
[2021-07-12 14:12:48,774] {logging_mixin.py:104} INFO - 3IINFOTECH.NS
[2021-07-12 14:12:48,778] {logging_mixin.py:104} INFO - 3i Infotech Limited (3IINFOTECH.NS)
[2021-07-12 14:13:24,182] {logging_mixin.py:104} INFO - 3MINDIA.NS
[2021-07-12 14:13:24,185] {logging_mixin.py:104} INFO - 3M India Limited (3MINDIA.NS)
[2021-07-12 14:14:01,602] {taskinstance.py:1481} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/seleniumtest.py", line 59, in extract
    ticker = str(ticker[0].text)
IndexError: list index out of range
[2021-07-12 14:14:01,717] {taskinstance.py:1531} INFO - Marking task as UP_FOR_RETRY. dag_id=ticker_yahoo, task_id=extract_task, execution_date=20210712T140931, start_date=20210712T141013, end_date=20210712T141401
[2021-07-12 14:14:01,966] {local_task_job.py:151} INFO - Task exited with return code 1
