[2021-07-15 14:00:09,705] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: psotgrressdftest.extract_trends 2021-07-15T13:57:00+00:00 [queued]>
[2021-07-15 14:00:09,766] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: psotgrressdftest.extract_trends 2021-07-15T13:57:00+00:00 [queued]>
[2021-07-15 14:00:09,778] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-15 14:00:09,780] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-07-15 14:00:09,783] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-15 14:00:09,843] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): extract_trends> on 2021-07-15T13:57:00+00:00
[2021-07-15 14:00:09,891] {standard_task_runner.py:52} INFO - Started process 3900 to run task
[2021-07-15 14:00:09,904] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'psotgrressdftest', 'extract_trends', '2021-07-15T13:57:00+00:00', '--job-id', '425', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/POSTGRESRSERS.py', '--cfg-path', '/tmp/tmp4ww2ipd2', '--error-file', '/tmp/tmpowqeqjke']
[2021-07-15 14:00:09,906] {standard_task_runner.py:77} INFO - Job 425: Subtask extract_trends
[2021-07-15 14:00:10,029] {logging_mixin.py:104} INFO - Running <TaskInstance: psotgrressdftest.extract_trends 2021-07-15T13:57:00+00:00 [running]> on host a2cbcfd4d6f4
[2021-07-15 14:00:10,208] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=psotgrressdftest
AIRFLOW_CTX_TASK_ID=extract_trends
AIRFLOW_CTX_EXECUTION_DATE=2021-07-15T13:57:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-15T13:57:00+00:00
[2021-07-15 14:00:10,238] {logging_mixin.py:104} INFO - ['20MICRONS.NS']
[2021-07-15 14:00:24,187] {logging_mixin.py:104} INFO - AAAAAAAAAAAAAAAAAAAAAAAAAAAA[0.0, 0.0, 0.0, 0.0, 0.0]
[2021-07-15 14:00:24,189] {taskinstance.py:1481} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/POSTGRESRSERS.py", line 147, in extract_trends
    cur.execute("UPDATE stages SET trendsStage = trendsStage + 1 WHERE keyword = '" + ticker.replace("'", "''") + "'")
NameError: name 'cur' is not defined
[2021-07-15 14:00:24,201] {taskinstance.py:1531} INFO - Marking task as FAILED. dag_id=psotgrressdftest, task_id=extract_trends, execution_date=20210715T135700, start_date=20210715T140009, end_date=20210715T140024
[2021-07-15 14:00:24,276] {local_task_job.py:151} INFO - Task exited with return code 1
