[2021-07-14 14:10:57,797] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: psotgrressdftest.news_extract 2021-07-14T14:10:45.815058+00:00 [queued]>
[2021-07-14 14:10:57,857] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: psotgrressdftest.news_extract 2021-07-14T14:10:45.815058+00:00 [queued]>
[2021-07-14 14:10:57,858] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-14 14:10:57,859] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-07-14 14:10:57,860] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-14 14:10:57,888] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): news_extract> on 2021-07-14T14:10:45.815058+00:00
[2021-07-14 14:10:57,922] {standard_task_runner.py:52} INFO - Started process 3544 to run task
[2021-07-14 14:10:57,935] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'psotgrressdftest', 'news_extract', '2021-07-14T14:10:45.815058+00:00', '--job-id', '248', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/POSTGRESRSERS.py', '--cfg-path', '/tmp/tmp88uor32w', '--error-file', '/tmp/tmpm4j80svk']
[2021-07-14 14:10:57,936] {standard_task_runner.py:77} INFO - Job 248: Subtask news_extract
[2021-07-14 14:10:58,062] {logging_mixin.py:104} INFO - Running <TaskInstance: psotgrressdftest.news_extract 2021-07-14T14:10:45.815058+00:00 [running]> on host a2cbcfd4d6f4
[2021-07-14 14:10:58,193] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=psotgrressdftest
AIRFLOW_CTX_TASK_ID=news_extract
AIRFLOW_CTX_EXECUTION_DATE=2021-07-14T14:10:45.815058+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-14T14:10:45.815058+00:00
[2021-07-14 14:10:58,226] {logging_mixin.py:104} INFO - The Aaron's Company, Inc.
[2021-07-14 14:11:27,536] {taskinstance.py:1481} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/POSTGRESRSERS.py", line 91, in news_extract
    cur.execute("UPDATE stages SET newsStage = newsStage + 1 WHERE keyword = '" + ticker + "'")
psycopg2.ProgrammingError: syntax error at or near "s"
LINE 1: ...sStage = newsStage + 1 WHERE keyword = 'The Aaron's Company,...
                                                             ^

[2021-07-14 14:11:27,545] {taskinstance.py:1531} INFO - Marking task as FAILED. dag_id=psotgrressdftest, task_id=news_extract, execution_date=20210714T141045, start_date=20210714T141057, end_date=20210714T141127
[2021-07-14 14:11:27,606] {local_task_job.py:151} INFO - Task exited with return code 1
