[2021-07-16 15:09:59,401] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: psotgrressdftest.select_ticker 2021-07-16T15:09:55.703203+00:00 [queued]>
[2021-07-16 15:09:59,430] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: psotgrressdftest.select_ticker 2021-07-16T15:09:55.703203+00:00 [queued]>
[2021-07-16 15:09:59,431] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-16 15:09:59,432] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-07-16 15:09:59,434] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-16 15:09:59,448] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): select_ticker> on 2021-07-16T15:09:55.703203+00:00
[2021-07-16 15:09:59,461] {standard_task_runner.py:52} INFO - Started process 2576 to run task
[2021-07-16 15:09:59,469] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'psotgrressdftest', 'select_ticker', '2021-07-16T15:09:55.703203+00:00', '--job-id', '768', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/POSTGRESRSERS.py', '--cfg-path', '/tmp/tmpoby_376p', '--error-file', '/tmp/tmpvm8q6inv']
[2021-07-16 15:09:59,471] {standard_task_runner.py:77} INFO - Job 768: Subtask select_ticker
[2021-07-16 15:09:59,536] {logging_mixin.py:104} INFO - Running <TaskInstance: psotgrressdftest.select_ticker 2021-07-16T15:09:55.703203+00:00 [running]> on host 13346afafa5b
[2021-07-16 15:09:59,616] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=psotgrressdftest
AIRFLOW_CTX_TASK_ID=select_ticker
AIRFLOW_CTX_EXECUTION_DATE=2021-07-16T15:09:55.703203+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-16T15:09:52.905130+00:00
[2021-07-16 15:09:59,634] {taskinstance.py:1481} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/POSTGRESRSERS.py", line 52, in select_ticker
    print(str(dag_run.state))
AttributeError: 'list' object has no attribute 'state'
[2021-07-16 15:09:59,644] {taskinstance.py:1531} INFO - Marking task as FAILED. dag_id=psotgrressdftest, task_id=select_ticker, execution_date=20210716T150955, start_date=20210716T150959, end_date=20210716T150959
[2021-07-16 15:09:59,680] {local_task_job.py:151} INFO - Task exited with return code 1
